plugins {
    id 'multiloader-common'
}

configurations {
    commonJava {
        canBeResolved = true
    }
    commonResources {
        canBeResolved = true
    }
}

dependencies {
    //better bundle
    if (project.name.contains("better-bundle")) {
        compileOnly(project(':common-better-bundle')) {
            capabilities {
                requireCapability "$group:$mod_id_better_bundle"
            }
        }
        commonJava project(path: ':common-better-bundle', configuration: 'commonJava')
        commonResources project(path: ':common-better-bundle', configuration: 'commonResources')
    } else {
        compileOnly(project(':common')) {
            capabilities {
                requireCapability "$group:$mod_id"
            }
        }
        commonJava project(path: ':common', configuration: 'commonJava')
        commonResources project(path: ':common', configuration: 'commonResources')
    }
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}
